# Nostr Compass - Technical resource for the Nostr protocol
#
# This config file is meant for settings that affect your whole site.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nostr Compass
email: info@nostrcompass.org

description: >-
  Technical resource for the Nostr protocol. Weekly newsletter covering NIP proposals,
  client updates, relay developments, and notable code changes.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nostrcompass.org" # the base hostname & protocol for your site
# twitter_username: nostrcompass
github_username: nostrcompass
# nostr:
#      - npub: YOUR_NPUB_HERE
repository_name: nostr-compass
bold: '**'
author: "Nostr Compass"  ## Default author name for blog posts

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/
   - Makefile
   - README.md
   - CONTRIBUTING.md

include: [".well-known"]

show_excerpts: true

defaults:
  - scope:
      path: ""  ## all pages
    values:
      image: https://nostrcompass.org/img/logos/compass-notext.svg
      breadcrumbs: true
      localizable: true
  - scope:
      path: "_topics"
    values:
      layout: topic
      permalink: /en/topics/:title/
      localizable: false

collections:
  topics:
    output: true

languages:
  - code: ja
    name: Japanese
  - code: es
    name: Spanish
  - code: pt
    name: Portuguese
  - code: zh
    name: Chinese
  - code: de
    name: German
  - code: fr
    name: French
